### ISSUE TITLE
500 error getting subjects in some projects

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-RestApi#97]
Some examples:
`https://radar-backend.co.uk/api/projects/radar-test/subjects`
`https://radar-backend.co.uk/api/projects/MS_TEST/subjects`
`https://radar-backend.co.uk/api/projects/radar-demo-1/subjects`

```
{"error":"server_error","message":"class java.lang.NullPointerException: null."}
```

//cc @kerzmaximilian

**Comment by nivemaham** [comment]
I have checked the logs and this is the reason we are getting null point exception. 
It is occurring when the service cannot calculate the value for `lastSeen`. I will investigate and push a fix. 
```
2018-06-18 08:00:37 UTC [-6] DEBUG - Empty cursor for collection source_statistics_syn_watch [org.radarcns.service.SourceMonitorService:79] 
2018-06-18 08:00:37 UTC [-6] DEBUG - Empty cursor for collection source_statistics_syn_watch [org.radarcns.service.SourceMonitorService:79] 
2018-06-18 08:00:37 UTC [-6] ERROR - [500] http://radar-backend.co.uk:80/api/projects/radar-demo-1/subjects [org.radarcns.webapp.exception.UncaughtExceptionMapper:32] 
java.lang.NullPointerException: null
	at org.radarcns.service.SubjectService.lambda$getLastSeenForSubject$1(SubjectService.java:76)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
```
